### ISSUE TITLE
Cannot read property 'channel' of undefined

### ISSUE THREAD

**Issue by almereyda** [Alex1990/wp2js#1]
After installing this with `npm i wp2js` and invoking a small script like

```
#!/usr/bin/env node

var wp2js = require('wp2js');

wp2js.parse({
    source: 'wordpress.xml',
    filterConfig: ['attachments']
}, function(err, data) {
  console.log(data)
});
```

with using Node 8.2.1 the following error is being thrown:

```
/.tmp/node_modules/wp2js/index.js:158
                    callback(null, xml.rss.channel[0]['generator'][0]);
                                          ^

TypeError: Cannot read property 'channel' of undefined
    at /home/ya/.tmp/node_modules/wp2js/index.js:158:43
    at /home/ya/.tmp/node_modules/async/lib/async.js:567:21
    at /home/ya/.tmp/node_modules/async/lib/async.js:246:17
    at /home/ya/.tmp/node_modules/async/lib/async.js:122:13
    at _each (/home/ya/.tmp/node_modules/async/lib/async.js:46:13)
    at async.each (/home/ya/.tmp/node_modules/async/lib/async.js:121:9)
    at _asyncMap (/home/ya/.tmp/node_modules/async/lib/async.js:245:13)
    at Object.map (/home/ya/.tmp/node_modules/async/lib/async.js:216:23)
    at _parallel (/home/ya/.tmp/node_modules/async/lib/async.js:565:20)
    at Object.async.parallel (/home/ya/.tmp/node_modules/async/lib/async.js:595:9)
```

Is this still compatible with the current versions of the dependencies?

**Comment by Alex1990** [comment]
While, this package is written three years ago and I didn't maintain it. Maybe the rss data structure of the wordpress is modified.
